[package]
name = "js_playground"
version = "0.5.0"
edition = "2021"

[features]
default = ["console"]
console = ["deno_console"]
web = ["deno_web"]

[dev-dependencies]
cargo-llvm-cov = "0.1.13"
version-sync = "0.9.4"
cargo-readme = "3.2.0"

[dependencies]
deno_core = "0.214.0"
serde = "1.0.188"
tokio = "1.32.0"

# Feature deps
deno_console = { version = "0.118.0", optional = true }
deno_web = { version = "0.150.0", optional = true }
