[package]
name = "ext_crypto"
description = "Module loader for deno_crypto"
edition.workspace = true
license.workspace = true
version.workspace = true
repository.workspace = true

[lib]
path = "lib.rs"

[dependencies]
deno_crypto = "0.137.0"
deno_core = { workspace = true }