name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    # Check if the README is up to date
    # We will do this before all the time-consuming tests
    - name: Check if the README is up to date.
      run: |
        cargo install cargo-rdme
        cargo rdme --check

    # Check formatting
    - name: Run fmt
      run: cargo fmt --check

    # Run default feature tests
    - name: Run tests
      run: cargo test --verbose --lib
    
    # Lint all the things
    - name: Run clippy
      run: cargo clippy --all-features

    # Run tests with no features
    - name: Run barebones tests
      run: cargo test --no-default-features --lib

    # Run tests with just web feature
    - name: Run web tests
      run: cargo test --features "web" --lib

    # Run tests with all features
    - name: Run complete tests
      run: cargo test --all-features --lib
